name: polaris_calendar
description: A modern calendar and todo application with intelligent chatbot integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.1.1
  file_picker: ^6.0.0
  image_picker: ^1.0.4
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  flutter_svg: ^2.0.9
  flutter_markdown: ^0.6.17+2
  dio: ^5.3.3
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  uuid: ^4.1.0
  syncfusion_flutter_calendar: ^23.1.43
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_quill: ^8.0.0
  file: ^7.0.0
  path: ^1.8.3
  dropdown_button2: ^2.3.9
  auto_size_text: ^3.0.0
  audio_waveforms: ^1.0.4
  record: ^5.0.1
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    # Uncomment this line if you add the .env file
    # - .env

  # Temporarily commented out until font files are added
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 